export const shopCategories = [
  { value: "electronics", label: "Electronics" },
  { value: "clothing", label: "Clothing & Apparel" },
  { value: "home_garden", label: "Home & Garden" },
  { value: "health_beauty", label: "Health & Beauty" },
  { value: "sports_outdoors", label: "Sports & Outdoors" },
  { value: "books_media", label: "Books & Media" },
  { value: "toys_games", label: "Toys & Games" },
  { value: "automotive", label: "Automotive" },
  { value: "jewelry_accessories", label: "Jewelry & Accessories" },
  { value: "food_beverages", label: "Food & Beverages" },
  { value: "art_craft", label: "Art & Craft Supplies" },
  { value: "baby_kids", label: "Baby & Kids" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "office_supplies", label: "Office Supplies" },
  { value: "music_instruments", label: "Music & Instruments" },
  { value: "furniture", label: "Furniture" },
  { value: "appliances", label: "Appliances" },
  { value: "shoes", label: "Shoes & Footwear" },
  { value: "bags_luggage", label: "Bags & Luggage" },
  { value: "tools_hardware", label: "Tools & Hardware" },
];
